# Stage 2: Run the application
FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy the JAR from the build stage
#COPY --from=build /app/target/*.jar app.jar

# Copy the JAR from your local target directory
COPY target/*.jar app.jar

# Expose the application's port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]

